language: node_js

node_js:
  - 4
  - 4.2.2

before_install: 
  - npm install -g grunt
  - npm install -g grunt-cli

install:
  - npm install
  - bower install

script: 
  - npm test

after_script:
  - node server.js